CARDS = [

# =====================
# СТАРШИЕ АРКАНЫ (22)
# =====================

{"name": "Шут","arcana": "major","keywords": ["начало","свобода","риск","неопытность"],
"general": "новый этап, открытость опыту и движение в неизвестность с доверием к происходящему",
"love": "легкие отношения или начало нового романа без лишних ожиданий и давления",
"career": "новое направление, обучение или старт в незнакомой сфере с возможностями роста",
"self": "доверие жизни, готовность идти вперед без страха ошибок",
"advice": "двигайся вперед, сохраняя осознанность и не теряя связи с реальностью",
"image_id": "AgACAgIAAxkBAAID_WnCkWsn9o8Ut6BUWRZBMJvYq7D0AAL-EWsbLWQZSo6dqWk2uLzoAQADAgADeQADOgQ"},

{"name": "Маг","arcana": "major","keywords": ["воля","инициатива","сила"],
"general": "способность управлять ситуацией, использовать ресурсы и направлять события в нужную сторону",
"love": "проявление инициативы в отношениях, активное влияние на развитие связи",
"career": "успешное управление процессами, использование навыков для достижения результата",
"self": "уверенность в своих силах и понимание, как влиять на реальность",
"advice": "действуй активно и используй все доступные возможности",
"image_id": "AgACAgIAAxkBAAID_2nCkY15c2zmreSo2g176JNzG3MDAAMSaxstZBlK_3lfpYxfx5wBAAMCAAN5AAM6BA"},

{"name": "Верховная Жрица","arcana": "major","keywords": ["интуиция","тайна"],
"general": "скрытые процессы, которые развиваются за пределами очевидного и требуют внутреннего понимания",
"love": "глубокая, но не всегда проявленная связь, где важна интуиция и чувствование партнера",
"career": "наблюдение и выжидательная позиция, работа с информацией и скрытыми аспектами",
"self": "сильная связь с внутренним голосом и чувствительность к тонким сигналам",
"advice": "доверяй интуиции и не спеши раскрывать все сразу",
"image_id": "AgACAgIAAxkBAAIEAWnCkdPou7jtsbS04O5bCfLpjJFmAAICEmsbLWQZSsTRFMAvpL4BAQADAgADeQADOgQ"},

{"name": "Императрица","arcana": "major","keywords": ["рост","изобилие"],
"general": "естественное развитие, изобилие и гармония, возникающие через заботу и внимание",
"love": "теплые, поддерживающие отношения с чувством комфорта и эмоциональной близости",
"career": "рост проекта или дела через постепенное развитие и вложенные усилия",
"self": "созидательная энергия, способность развивать и приумножать ресурсы",
"advice": "заботься о том, что важно, и позволяй процессам развиваться естественно",
"image_id": "AgACAgIAAxkBAAIEA2nCke6XW1omnevN4z4FSbgvZttFAAIFEmsbLWQZSoSg-7UNTtBhAQADAgADeQADOgQ"},

{"name": "Император","arcana": "major","keywords": ["контроль","структура"],
"general": "стабильность, порядок и управление ситуацией через четкие решения и границы",
"love": "серьезные отношения, основанные на ответственности и стремлении к устойчивости",
"career": "руководство, контроль процессов и выстраивание системы",
"self": "дисциплина, внутренняя опора и умение держать ситуацию под контролем",
"advice": "возьми ответственность и выстрой четкую структуру действий",
"image_id": "AgACAgIAAxkBAAIEBWnCkgABjjbCsJ3joRkk5omlx2k3eAACBxJrGy1kGUqpzurBKpUEmwEAAwIAA3kAAzoE"},

{"name": "Иерофант","arcana": "major","keywords": ["традиции","духовность"],
"general": "следование правилам, обучение и опора на проверенные знания и ценности",
"love": "традиционный союз, ориентированный на стабильность и общие принципы",
"career": "наставничество, обучение или работа в рамках системы и правил",
"self": "формирование ценностей и поиск смысла через опыт и знания",
"advice": "обратись к опыту и не игнорируй проверенные подходы",
"image_id": "AgACAgIAAxkBAAIEB2nCkhIAAbleSQ9P64RwZgcUQ618FgACCBJrGy1kGUpStO58F4xGXAEAAwIAA3kAAzoE"},

{"name": "Влюбленные","arcana": "major","keywords": ["выбор","любовь"],
"general": "необходимость сделать важный выбор, который повлияет на дальнейший путь",
"love": "сильная эмоциональная связь, требующая искренности и осознанного решения",
"career": "принятие решения между вариантами или направлениями",
"self": "внутренний конфликт или объединение противоположностей",
"advice": "делай выбор осознанно, опираясь на свои истинные чувства",
"image_id": "AgACAgIAAxkBAAIECWnCkiR12QiUgHY7lLqkmUniSaF_AAIJEmsbLWQZShNbRmMKi2W8AQADAgADeQADOgQ"},

{"name": "Колесница","arcana": "major","keywords": ["движение","победа"],
"general": "активное движение к цели, преодоление препятствий и контроль над ситуацией",
"love": "развитие отношений через усилия и совместное движение вперед",
"career": "прорыв, достижение результата благодаря настойчивости и контролю",
"self": "сильная воля и способность направлять себя в нужную сторону",
"advice": "не сдавайся и сохраняй фокус на цели",
"image_id": "AgACAgIAAxkBAAIEC2nCkjzxCME3f7QnAQqC8HLdNSSUAAIKEmsbLWQZSrdh2cjoZduxAQADAgADeQADOgQ"},

{"name": "Сила","arcana": "major","keywords": ["терпение","контроль"],
"general": "мягкая внутренняя сила, позволяющая управлять ситуацией без давления",
"love": "глубокая связь, основанная на принятии, терпении и эмоциональной зрелости",
"career": "устойчивость и способность справляться с трудностями без резких действий",
"self": "контроль эмоций и внутренняя гармония",
"advice": "сохраняй спокойствие и действуй мягко, но уверенно",
"image_id": "AgACAgIAAxkBAAIEDWnCklXCxmNAp5RT4IDowPiGwTQdAAINEmsbLWQZSqMYcAgdt9SkAQADAgADeQADOgQ"},

{"name": "Отшельник","arcana": "major","keywords": ["поиск","одиночество"],
"general": "период уединения и внутреннего поиска, необходимый для понимания ситуации",
"love": "дистанция или необходимость разобраться в себе перед развитием отношений",
"career": "анализ, пересмотр стратегии и поиск правильного направления",
"self": "глубокий поиск истины и понимание своих внутренних процессов",
"advice": "замедлись и обрати внимание на внутренние ответы",
"image_id": "AgACAgIAAxkBAAIED2nCkmW-C-8VipJbptVb4WII4bLPAAIPEmsbLWQZSut4qt2mJHpvAQADAgADeQADOgQ"},

{"name": "Колесо Фортуны","arcana": "major","keywords": ["перемены","судьба"],
"general": "поворот событий, изменения, которые происходят независимо от контроля",
"love": "судьбоносные встречи или неожиданные изменения в отношениях",
"career": "удачные возможности или смена обстоятельств",
"self": "осознание цикличности жизни и изменений",
"advice": "доверься процессу и будь готов к переменам",
"image_id": "AgACAgIAAxkBAAIEEWnCkncjdmWbP9EJbryNz1RWfRLHAAIQEmsbLWQZSmO1NxG8GE-qAQADAgADeQADOgQ"},

{"name": "Справедливость","arcana": "major","keywords": ["баланс","закон"],
"general": "необходимость честной оценки ситуации и восстановления баланса",
"love": "равновесие в отношениях и честность между партнерами",
"career": "принятие объективных решений и ответственность за действия",
"self": "осознание последствий своих поступков",
"advice": "будь честен с собой и другими, принимай справедливые решения",
"image_id": "AgACAgIAAxkBAAIEE2nCkoehAbbUxrk6nEs9xKMs6vR_AAISEmsbLWQZSk4qjmY1s8toAQADAgADeQADOgQ"},

{"name": "Повешенный","arcana": "major","keywords": ["пауза","жертва"],
"general": "вынужденная пауза или задержка, требующая пересмотра взгляда на ситуацию",
"love": "ожидание или состояние неопределенности в отношениях",
"career": "стагнация, необходимость остановиться и переоценить подход",
"self": "изменение восприятия и новый взгляд на привычные вещи",
"advice": "отпусти контроль и попробуй посмотреть на ситуацию иначе",
"image_id": "AgACAgIAAxkBAAIEFWnCkpdJ3-UtughRQKeZ9TLf9UQpAAITEmsbLWQZSmxWWxProfHDAQADAgADeQADOgQ"},

{"name": "Смерть","arcana": "major","keywords": ["конец","трансформация"],
"general": "завершение одного этапа и переход к новому через глубокие изменения",
"love": "конец старого формата отношений или их полное обновление",
"career": "смена направления, завершение проекта или переход на новый уровень",
"self": "внутреннее перерождение и освобождение от прошлого",
"advice": "прими изменения и не держись за то, что уже завершилось",
"image_id": "AgACAgIAAxkBAAIEF2nCkq1Z5Z5ZJKa-AmRoko0pE269AAIUEmsbLWQZSphgqX73bAYWAQADAgADeQADOgQ"},

{"name": "Умеренность","arcana": "major","keywords": ["баланс","гармония"],
"general": "плавное выравнивание ситуации и достижение внутреннего и внешнего равновесия",
"love": "спокойные, гармоничные отношения без крайностей",
"career": "постепенное развитие без резких скачков",
"self": "внутренняя гармония и умение сохранять баланс",
"advice": "избегай крайностей и действуй умеренно",
"image_id": "AgACAgIAAxkBAAIEGWnCksEByxTy2NwtWMu3FZacf2s3AAIVEmsbLWQZSooAAXB6kALP3gEAAwIAA3kAAzoE"},

{"name": "Дьявол","arcana": "major","keywords": ["зависимость"],
"general": "ограничения, привязанности или ситуации, из которых сложно выйти",
"love": "токсичные или зависимые отношения",
"career": "привязка к работе или обстоятельствам, ограничивающим свободу",
"self": "зависимости, страхи или внутренние блоки",
"advice": "осознай, что тебя удерживает, и постарайся освободиться",
"image_id": "AgACAgIAAxkBAAIEG2nCktXPAQ7yiRlEaqBJbAsMeaphAAIWEmsbLWQZSqA2cg7snkkfAQADAgADeQADOgQ"},

{"name": "Башня","arcana": "major","keywords": ["кризис"],
"general": "резкое разрушение старых структур и неожиданное изменение ситуации",
"love": "конфликт или кризис, вскрывающий скрытые проблемы",
"career": "крах прежних планов и необходимость перестройки",
"self": "разрушение старых убеждений и взглядов",
"advice": "прими перемены, даже если они происходят резко и неожиданно",
"image_id": "AgACAgIAAxkBAAIEHWnCkutPz3FTa2HlYVBT9b_BuHTCAAIXEmsbLWQZSigfBIMQIPvUAQADAgADeQADOgQ"},

{"name": "Звезда","arcana": "major","keywords": ["надежда"],
"general": "восстановление, надежда и постепенное улучшение ситуации",
"love": "исцеление отношений и мягкое восстановление связи",
"career": "появление перспектив и ощущение движения к лучшему",
"self": "вдохновение и внутреннее обновление",
"advice": "сохраняй веру и продолжай двигаться вперед",
"image_id": "AgACAgIAAxkBAAIEH2nCkvrIZUZcujd0bfoOUFovP7XBAAIZEmsbLWQZSm3OWpKDsU7PAQADAgADeQADOgQ"},

{"name": "Луна","arcana": "major","keywords": ["иллюзии"],
"general": "неясность ситуации, скрытые факторы и искажение восприятия",
"love": "сомнения, страхи или недосказанность в отношениях",
"career": "обман, путаница или отсутствие полной картины",
"self": "внутренние страхи и работа с подсознанием",
"advice": "проверяй факты и не делай выводов на основе эмоций",
"image_id": "AgACAgIAAxkBAAIEIWnCkw2yjckHL3xwK8ljsyRa3qijAAIaEmsbLWQZShcdylA6hEKWAQADAgADeQADOgQ"},

{"name": "Солнце","arcana": "major","keywords": ["успех"],
"general": "радость, ясность и благоприятный исход ситуации",
"love": "счастливые, открытые и гармоничные отношения",
"career": "успех, признание и положительный результат",
"self": "энергия, уверенность и внутренний подъем",
"advice": "наслаждайся моментом и не скрывай свою радость",
"image_id": "AgACAgIAAxkBAAIEI2nCkxwx6O_0UAhHH0jgPpynnrhuAAIbEmsbLWQZSsIydaSgoJySAQADAgADeQADOgQ"},

{"name": "Суд","arcana": "major","keywords": ["итоги"],
"general": "подведение итогов и переход на новый уровень через осознание опыта",
"love": "возвращение к прошлым отношениям или их переоценка",
"career": "результат усилий и важный этап переосмысления",
"self": "внутреннее пробуждение и осознание своего пути",
"advice": "сделай выводы и не игнорируй полученный опыт",
"image_id": "AgACAgIAAxkBAAIEJWnCkyueJ57C-1JuZsrXzjSlb0rQAAIcEmsbLWQZSnUk279ntsTbAQADAgADeQADOgQ"},

{"name": "Мир","arcana": "major","keywords": ["завершение"],
"general": "успешное завершение этапа и достижение целостного результата",
"love": "гармония, завершенность и устойчивость в отношениях",
"career": "достижение цели и выход на новый уровень",
"self": "ощущение целостности и внутреннего баланса",
"advice": "насладись результатом и признай свой путь",
"image_id": "AgACAgIAAxkBAAIEJ2nCkzrE0hF3hsvz7WmOCPCEK1XZAAIdEmsbLWQZSsz9erMRsyNeAQADAgADeQADOgQ"},

# =====================
# ЖЕЗЛЫ (14)
# =====================

{"name":"Туз Жезлов","arcana":"minor","suit":"wands","keywords":["начало"],
"general":"мощный импульс к началу нового дела, вдохновение и внутренняя готовность действовать",
"love":"сильное притяжение, вспышка страсти или начало яркого романа",
"career":"старт нового проекта или идеи с большим потенциалом роста",
"self":"прилив энергии, вдохновение и желание двигаться вперед",
"advice":"используй момент и начинай действовать, пока есть импульс",
"image_id":"AgACAgIAAxkBAAIEKWnCk0vkOEKNj-HZ-tTEHl8VI_lNAAIeEmsbLWQZSl91n875j866AQADAgADeQADOgQ"},

{"name":"Двойка Жезлов","arcana":"minor","suit":"wands","keywords":["выбор"],
"general":"планирование будущего и выбор направления для дальнейших действий",
"love":"сомнения или необходимость определить, куда движутся отношения",
"career":"разработка стратегии и оценка возможных вариантов развития",
"self":"внутреннее решение о следующем шаге",
"advice":"определи цель и выбери направление без колебаний",
"image_id":"AgACAgIAAxkBAAIEK2nCk181_0UQX4Gkr1alxDd8G9MyAAIfEmsbLWQZStK3x9SoMyZZAQADAgADeQADOgQ"},

{"name":"Тройка Жезлов","arcana":"minor","suit":"wands","keywords":["рост"],
"general":"расширение возможностей и движение вперед после первых результатов",
"love":"развитие отношений и переход на новый уровень",
"career":"рост и появление новых перспектив благодаря ранее вложенным усилиям",
"self":"уверенность в выбранном пути и ожидание результатов",
"advice":"продолжай двигаться вперед и расширяй свои возможности",
"image_id":"AgACAgIAAxkBAAIELWnCk2_fv5mmkyrPLGLsKCbDwXLfAAIhEmsbLWQZSiT0i9bLcKGlAQADAgADeQADOgQ"},

{"name":"Четверка Жезлов","arcana":"minor","suit":"wands","keywords":["радость"],
"general":"стабильный успех и период гармонии после достигнутых результатов",
"love":"укрепление союза, чувство стабильности и общая радость",
"career":"достижение этапа, который можно считать значимым результатом",
"self":"удовлетворение и ощущение внутреннего комфорта",
"advice":"позволь себе остановиться и отметить достигнутое",
"image_id":"AgACAgIAAxkBAAIEL2nCk36fd-lq-ox9_agYCE-Uk4q7AAIiEmsbLWQZSiaJy2l11bdrAQADAgADeQADOgQ"},

{"name":"Пятерка Жезлов","arcana":"minor","suit":"wands","keywords":["конфликт"],
"general":"соперничество и столкновение интересов, создающее напряжение",
"love":"ссоры, недопонимание или борьба за внимание",
"career":"конкуренция и необходимость отстаивать свои позиции",
"self":"внутреннее напряжение и ощущение борьбы",
"advice":"не трать силы на бессмысленные споры и выбирай важные битвы",
"image_id":"AgACAgIAAxkBAAIEMWnCk4z1xiJaIYUWpqq9yy_bTdvaAAIjEmsbLWQZSqjqlNE0HLmxAQADAgADeQADOgQ"},

{"name":"Шестерка Жезлов","arcana":"minor","suit":"wands","keywords":["победа"],
"general":"успешный результат и признание со стороны окружающих",
"love":"гармония и чувство уверенности в отношениях",
"career":"признание заслуг, достижение цели и позитивная оценка",
"self":"уверенность в себе и ощущение победы",
"advice":"прими успех и не обесценивай свои достижения",
"image_id":"AgACAgIAAxkBAAIEM2nCk5vj_7dzWI5MmZo3rVv80jUOAAIkEmsbLWQZSsUxMA8FyvYGAQADAgADeQADOgQ"},

{"name":"Семерка Жезлов","arcana":"minor","suit":"wands","keywords":["защита"],
"general":"необходимость удерживать свою позицию и защищать достигнутое",
"love":"борьба за отношения или необходимость отстаивать границы",
"career":"отстаивание своих идей и позиции в условиях давления",
"self":"стойкость и готовность не уступать",
"advice":"держись своей позиции и не сдавайся под давлением",
"image_id":"AgACAgIAAxkBAAIENWnCk6yDUpcrggL1ZsGVPvVgPkHzAAIlEmsbLWQZSk6MIZ9h23gzAQADAgADeQADOgQ"},

{"name":"Восьмерка Жезлов","arcana":"minor","suit":"wands","keywords":["скорость"],
"general":"быстрое развитие событий и стремительное движение вперед",
"love":"ускорение отношений, быстрое сближение",
"career":"прогресс, быстрые изменения и активное развитие проектов",
"self":"высокий уровень энергии и готовность действовать",
"advice":"действуй быстро и не упускай возможности",
"image_id":"AgACAgIAAxkBAAIEN2nCk7w6HgpGL8tBZJ4qEFD0Z9hmAAImEmsbLWQZSi_cxvPXiQybAQADAgADeQADOgQ"},

{"name":"Девятка Жезлов","arcana":"minor","suit":"wands","keywords":["усталость"],
"general":"напряжение после долгой борьбы и необходимость сохранять защиту",
"love":"осторожность и недоверие из-за прошлого опыта",
"career":"усталость от нагрузки, но необходимость довести дело до конца",
"self":"внутренняя защита и готовность к новым трудностям",
"advice":"держись, но не забывай беречь свои ресурсы",
"image_id":"AgACAgIAAxkBAAIEOWnCk8o5P_Mgvnmxr6Cozf0I5xy9AAInEmsbLWQZSgQmbnQvJumIAQADAgADeQADOgQ"},

{"name":"Десятка Жезлов","arcana":"minor","suit":"wands","keywords":["нагрузка"],
"general":"перегрузка обязанностями и ощущение давления",
"love":"напряжение в отношениях из-за накопившихся проблем",
"career":"переработка и чрезмерная ответственность",
"self":"усталость и ощущение, что слишком многое взято на себя",
"advice":"сними лишнюю нагрузку и расставь приоритеты",
"image_id":"AgACAgIAAxkBAAIEO2nCk9_lmTKd3_m8gxIXJU_iiPudAAIoEmsbLWQZSg0guoqZGQ-VAQADAgADeQADOgQ"},

{"name":"Паж Жезлов","arcana":"minor","suit":"wands","keywords":["новость"],
"general":"появление новой идеи или импульса к действию",
"love":"новое чувство или интерес, который только начинает развиваться",
"career":"старт идеи или проекта с потенциалом",
"self":"энтузиазм и желание исследовать новое",
"advice":"будь открыт новому и пробуй разные возможности",
"image_id":"AgACAgIAAxkBAAIEPWnCk-86dEksS2l4MoBcZrUu_se_AAIpEmsbLWQZSv0Kl2qbX5ehAQADAgADeQADOgQ"},

{"name":"Рыцарь Жезлов","arcana":"minor","suit":"wands","keywords":["действие"],
"general":"сильный импульс к действию и стремительное движение вперед",
"love":"страсть, но возможная нестабильность из-за импульсивности",
"career":"активность, быстрые решения и желание продвигаться вперед",
"self":"импульсивность и стремление действовать без долгих раздумий",
"advice":"не спеши и контролируй свои действия",
"image_id":"AgACAgIAAxkBAAIEP2nCk_-NX9-HlgR0c61bIUNMfbAOAAIqEmsbLWQZSugTXmP8YItSAQADAgADeQADOgQ"},

{"name":"Королева Жезлов","arcana":"minor","suit":"wands","keywords":["харизма"],
"general":"уверенность, притягательность и способность вдохновлять других",
"love":"сильная привлекательность и уверенность в отношениях",
"career":"лидерство через харизму и уверенное поведение",
"self":"внутренняя сила и уверенность в себе",
"advice":"проявись открыто и не скрывай свою силу",
"image_id":"AgACAgIAAxkBAAIEQWnClBVzOtkp2GXMO2BxF_sHe8lkAAIrEmsbLWQZSohs8LeqlAoLAQADAgADeQADOgQ"},

{"name":"Король Жезлов","arcana":"minor","suit":"wands","keywords":["лидерство"],
"general":"уверенное управление ситуацией и стратегическое мышление",
"love":"доминирование или ведущая роль в отношениях",
"career":"управление, ответственность и контроль над процессами",
"self":"сила, уверенность и способность вести за собой",
"advice":"бери ответственность и действуй как лидер",
"image_id":"AgACAgIAAxkBAAIEQ2nClCfyYn82eYEsYYyomgSTdGhvAAIsEmsbLWQZSi8lsd5xSKvGAQADAgADeQADOgQ"},

# =====================
# КУБКИ (14)
# =====================

{"name":"Туз Кубков","arcana":"minor","suit":"cups","keywords":["эмоции"],
"general":"зарождение новых чувств, эмоциональное открытие и состояние внутреннего наполнения",
"love":"влюбленность, искренние эмоции и начало глубокой эмоциональной связи",
"career":"вдохновение, появление идеи, связанной с внутренним откликом и интересом",
"self":"открытость чувствам и готовность принимать и отдавать эмоции",
"advice":"доверяй своим чувствам и не закрывайся от того, что приходит",
"image_id":"AgACAgIAAxkBAAIERWnClabSvj0vSVAWm4EgSeKIu8nGAAIxEmsbLWQZSk_iC96GThd5AQADAgADeQADOgQ"},

{"name":"Двойка Кубков","arcana":"minor","suit":"cups","keywords":["союз"],
"general":"гармоничная связь и взаимное притяжение, основанное на равенстве и понимании",
"love":"глубокая эмоциональная гармония и взаимность чувств",
"career":"партнерство, основанное на доверии и совпадении интересов",
"self":"внутренний баланс и ощущение целостности через взаимодействие",
"advice":"доверяй этой связи и развивай ее через искренность",
"image_id":"AgACAgIAAxkBAAIER2nClbv-pGO9UeN6LVbmqcM7AdAkAAIyEmsbLWQZSiSNwhS4esz4AQADAgADeQADOgQ"},

{"name":"Тройка Кубков","arcana":"minor","suit":"cups","keywords":["радость"],
"general":"праздничная атмосфера, легкость и радость от общения с близкими",
"love":"общение, флирт и приятное эмоциональное взаимодействие",
"career":"командная работа и поддержка со стороны окружения",
"self":"легкость, открытость и желание делиться эмоциями",
"advice":"раздели радость с другими и не замыкайся в себе",
"image_id":"AgACAgIAAxkBAAIESWnClckdIn6jTOKq7Qd6jYjpzUCbAAIzEmsbLWQZShg_XSwxQx6GAQADAgADeQADOgQ"},

{"name":"Четверка Кубков","arcana":"minor","suit":"cups","keywords":["апатия"],
"general":"ощущение неудовлетворенности и игнорирование доступных возможностей",
"love":"скука или эмоциональная закрытость в отношениях",
"career":"потеря интереса к текущей деятельности и отсутствие вовлеченности",
"self":"апатия и погруженность в свои мысли",
"advice":"посмотри шире и обрати внимание на то, что ты не замечаешь",
"image_id":"AgACAgIAAxkBAAIES2nCldfMbRTMY4OCll2LSawCvVzrAAI1EmsbLWQZSojrQvmceX8eAQADAgADeQADOgQ"},

{"name":"Пятерка Кубков","arcana":"minor","suit":"cups","keywords":["потеря"],
"general":"сожаление о прошлом и фиксация на утрате вместо оставшихся возможностей",
"love":"разочарование и переживание из-за эмоциональных потерь",
"career":"ощущение неудачи или упущенных возможностей",
"self":"печаль и склонность застревать в негативных эмоциях",
"advice":"смотри вперед и не игнорируй то, что еще остается",
"image_id":"AgACAgIAAxkBAAIETWnCleQvPNOEYhTS5cLDZ5sqOY-YAAI2EmsbLWQZSh_jfyN1DD2iAQADAgADeQADOgQ"},

{"name":"Шестерка Кубков","arcana":"minor","suit":"cups","keywords":["прошлое"],
"general":"возвращение к прошлому, ностальгия и воспоминания о значимых моментах",
"love":"возвращение старых чувств или связь с прошлым партнером",
"career":"обращение к старым проектам или опыту",
"self":"погружение в воспоминания и поиск опоры в прошлом",
"advice":"вспомни важное, но не застревай в прошлом",
"image_id":"AgACAgIAAxkBAAIET2nClfVJkebo8i8yukiIchwNaZvwAAI4EmsbLWQZSovg7KZ68bCBAQADAgADeQADOgQ"},

{"name":"Семерка Кубков","arcana":"minor","suit":"cups","keywords":["иллюзии"],
"general":"избыток вариантов и неясность, мешающая принять решение",
"love":"сомнения и иллюзии относительно чувств или партнера",
"career":"неясные перспективы и сложность выбора направления",
"self":"мечты и склонность уходить в фантазии",
"advice":"будь реалистом и отделяй желания от реальности",
"image_id":"AgACAgIAAxkBAAIEUWnClgPn0TbiUVajjS5s3uMrGOK9AAI5EmsbLWQZSkcPvyxtE57TAQADAgADeQADOgQ"},

{"name":"Восьмерка Кубков","arcana":"minor","suit":"cups","keywords":["уход"],
"general":"осознанный уход от ситуации, которая больше не приносит удовлетворения",
"love":"разрыв или эмоциональное отдаление ради поиска чего-то более глубокого",
"career":"уход с текущего места или смена направления",
"self":"внутренний поиск и желание найти более значимый путь",
"advice":"отпусти прошлое и двигайся туда, где есть смысл",
"image_id":"AgACAgIAAxkBAAIEU2nClg4rPLV2ciI1tCSSsK3KNRmUAAI6EmsbLWQZSt9X7w9zZHPXAQADAgADeQADOgQ"},

{"name":"Девятка Кубков","arcana":"minor","suit":"cups","keywords":["желание"],
"general":"исполнение желаний и ощущение эмоционального удовлетворения",
"love":"радость, комфорт и удовлетворенность в отношениях",
"career":"успех, приносящий внутреннее удовлетворение",
"self":"ощущение полноты и удовольствия от текущего состояния",
"advice":"наслаждайся тем, что уже достигнуто",
"image_id":"AgACAgIAAxkBAAIEVWnClh2f30oz44M_1jcnUlA0IbXDAAI7EmsbLWQZSjbBt3zroMSvAQADAgADeQADOgQ"},

{"name":"Десятка Кубков","arcana":"minor","suit":"cups","keywords":["счастье"],
"general":"гармония, эмоциональная полнота и ощущение завершенности",
"love":"семейное счастье, глубокая эмоциональная связь и стабильность",
"career":"удовлетворение от работы и гармония в окружении",
"self":"радость, внутренний покой и ощущение целостности",
"advice":"цени близких и сохраняй то, что приносит тебе счастье",
"image_id":"AgACAgIAAxkBAAIEV2nClin0brTA7QaPcNjqtgYpXZZ-AAI8EmsbLWQZShjW6kr4UBdjAQADAgADeQADOgQ"},

{"name":"Паж Кубков","arcana":"minor","suit":"cups","keywords":["романтика"],
"general":"новость или эмоциональный импульс, связанный с чувствами",
"love":"зарождение чувств, романтичный настрой и искренность",
"career":"вдохновение и новые идеи, связанные с творчеством",
"self":"открытость, чувствительность и готовность к новому опыту",
"advice":"будь искренним и не бойся проявлять свои чувства",
"image_id":"AgACAgIAAxkBAAIEWWnClkk_Mdhqx8lsHIjmsZcZYfl3AAI9EmsbLWQZSgEJ6sg942hrAQADAgADeQADOgQ"},

{"name":"Рыцарь Кубков","arcana":"minor","suit":"cups","keywords":["идеализм"],
"general":"движение, основанное на чувствах и внутреннем отклике",
"love":"романтические проявления, ухаживания и идеализация партнера",
"career":"творческий подход и следование вдохновению",
"self":"мечты и стремление к идеальному состоянию",
"advice":"следуй сердцу, но не теряй связь с реальностью",
"image_id":"AgACAgIAAxkBAAIEW2nClmZf4dpOZvIhKdZdYwqCSayyAAI-EmsbLWQZSmuPqcSm95FTAQADAgADeQADOgQ"},

{"name":"Королева Кубков","arcana":"minor","suit":"cups","keywords":["эмпатия"],
"general":"глубокое понимание чувств и способность поддерживать других",
"love":"забота, эмоциональная зрелость и чуткость в отношениях",
"career":"понимание людей и работа с эмоциональными аспектами",
"self":"сильная интуиция и эмоциональная глубина",
"advice":"доверяй своим чувствам и внутреннему знанию",
"image_id":"AgACAgIAAxkBAAIEXWnClnfr4O-5ObD86J-h8pdmbKVrAAI_EmsbLWQZSk_QxhDLWnbDAQADAgADeQADOgQ"},

{"name":"Король Кубков","arcana":"minor","suit":"cups","keywords":["баланс"],
"general":"эмоциональная зрелость и способность сохранять спокойствие в любой ситуации",
"love":"стабильные, глубокие отношения с эмоциональной поддержкой",
"career":"мудрое управление и умение учитывать человеческий фактор",
"self":"контроль эмоций и внутренняя устойчивость",
"advice":"сохраняй баланс между чувствами и разумом",
"image_id":"AgACAgIAAxkBAAIEX2nClonBH-CP1BtQ1lm3YmUcWR9sAAJAEmsbLWQZSo_QyJeZomLAAQADAgADeQADOgQ"},

# =====================
# МЕЧИ (14)
# =====================

{"name":"Туз Мечей","arcana":"minor","suit":"swords","keywords":["истина"],
"general":"прояснение ситуации, появление истины и ясного понимания происходящего",
"love":"честность и открытый разговор, который проясняет отношения",
"career":"идея или решение, которое вносит ясность и определенность",
"self":"осознание, внутреннее прояснение и понимание сути",
"advice":"говори правду и не избегай ясности, даже если она непроста",
"image_id":"AgACAgIAAxkBAAIEYWnCltU15A8AATufu_hA5NBDDYWbTwACQxJrGy1kGUoVYRYwholRbgEAAwIAA3kAAzoE"},

{"name":"Двойка Мечей","arcana":"minor","suit":"swords","keywords":["выбор"],
"general":"сомнения и внутренний конфликт, мешающий принять решение",
"love":"неопределенность и нежелание видеть реальное положение дел",
"career":"задержка из-за отсутствия ясного решения",
"self":"внутренний конфликт и избегание выбора",
"advice":"перестань откладывать и прими решение, даже если оно сложное",
"image_id":"AgACAgIAAxkBAAIEY2nCluUcno1IMsYAAcoZTn9r9rszHAACRBJrGy1kGUp_fUoMOunbNwEAAwIAA3kAAzoE"},

{"name":"Тройка Мечей","arcana":"minor","suit":"swords","keywords":["боль"],
"general":"эмоциональная боль, разрыв или неприятная правда",
"love":"разбитое сердце, разочарование или болезненное осознание",
"career":"разочарование из-за неудачи или конфликтной ситуации",
"self":"переживания и необходимость прожить болезненные чувства",
"advice":"не подавляй эмоции, проживи их и дай себе время восстановиться",
"image_id":"AgACAgIAAxkBAAIEZWnClvEpIfjQyKbrcc0pPTbJEx-bAAJGEmsbLWQZSs17z7hgXJjBAQADAgADeQADOgQ"},

{"name":"Четверка Мечей","arcana":"minor","suit":"swords","keywords":["пауза"],
"general":"период восстановления, пауза после напряжения",
"love":"временная дистанция или необходимость отдохнуть от эмоций",
"career":"отдых или пауза перед следующим этапом",
"self":"усталость и необходимость восстановления ресурсов",
"advice":"дай себе время на отдых и не форсируй события",
"image_id":"AgACAgIAAxkBAAIEZ2nClv4g_c59lbFd1q5w64wO6issAAJHEmsbLWQZSi8dG_rkM_qtAQADAgADeQADOgQ"},

{"name":"Пятерка Мечей","arcana":"minor","suit":"swords","keywords":["конфликт"],
"general":"напряжение и конфликт, в котором нет настоящей победы",
"love":"ссоры и борьба за правоту, разрушающая связь",
"career":"борьба за позицию или конфликт в коллективе",
"self":"агрессия или внутреннее напряжение",
"advice":"не дави и не стремись выиграть любой ценой",
"image_id":"AgACAgIAAxkBAAIEaWnClwwCblVuFYgt3qHbTzyEBILHAAJIEmsbLWQZSgyUcohDuEl4AQADAgADeQADOgQ"},

{"name":"Шестерка Мечей","arcana":"minor","suit":"swords","keywords":["переход"],
"general":"переход к более спокойному состоянию после трудного периода",
"love":"дистанция или постепенное восстановление после напряжения",
"career":"смена условий или движение к более стабильной ситуации",
"self":"внутренний уход от проблем и поиск спокойствия",
"advice":"двигайся дальше и не возвращайся к прошлым трудностям",
"image_id":"AgACAgIAAxkBAAIEa2nClxy3JEa4rCvIx1QomwWMkVtuAAJLEmsbLWQZSkUTRq8d0zTRAQADAgADeQADOgQ"},

{"name":"Семерка Мечей","arcana":"minor","suit":"swords","keywords":["обман"],
"general":"скрытые действия, хитрость или попытка обойти ситуацию",
"love":"недоверие, недосказанность или скрытые мотивы",
"career":"манипуляции или нечестные действия",
"self":"уклонение от ответственности или честного взгляда на ситуацию",
"advice":"будь честен с собой и не действуй скрытно",
"image_id":"AgACAgIAAxkBAAIEbWnClyeEusoxXgKWz8csbwkOavlYAAJMEmsbLWQZSnmp9ZbPKMX7AQADAgADeQADOgQ"},

{"name":"Восьмерка Мечей","arcana":"minor","suit":"swords","keywords":["ограничение"],
"general":"ощущение ограничений, которые часто создаются внутренними страхами",
"love":"страхи и неуверенность, мешающие развитию отношений",
"career":"застой из-за внутренних барьеров или сомнений",
"self":"скованность и ощущение невозможности изменить ситуацию",
"advice":"расширь границы восприятия и пересмотри свои убеждения",
"image_id":"AgACAgIAAxkBAAIEb2nClzPbS3UYjX6xt9TG6UNXeEi8AAJNEmsbLWQZSgNjwFcEKsMXAQADAgADeQADOgQ"},

{"name":"Девятка Мечей","arcana":"minor","suit":"swords","keywords":["тревога"],
"general":"сильные переживания, тревожные мысли и внутреннее напряжение",
"love":"переживания и страхи, связанные с отношениями",
"career":"стресс и переутомление из-за давления",
"self":"беспокойство и склонность накручивать себя",
"advice":"успокойся и не усиливай тревогу мыслями",
"image_id":"AgACAgIAAxkBAAIEcWnClz_FfMVKaNBBxbhTe3ujp60yAAJOEmsbLWQZSog0Py978vHfAQADAgADeQADOgQ"},

{"name":"Десятка Мечей","arcana":"minor","suit":"swords","keywords":["конец"],
"general":"резкое завершение ситуации и точка невозврата",
"love":"разрыв или окончание болезненного этапа",
"career":"провал или завершение проекта",
"self":"обнуление и освобождение через завершение",
"advice":"прими конец как начало нового этапа",
"image_id":"AgACAgIAAxkBAAIEc2nCl0lZ4z0KnuMZIVCMrEHWVMITAAJREmsbLWQZSrGP3DJt6mOnAQADAgADeQADOgQ"},

{"name":"Паж Мечей","arcana":"minor","suit":"swords","keywords":["наблюдение"],
"general":"сбор информации и внимательное наблюдение за ситуацией",
"love":"интерес и желание разобраться в партнере",
"career":"обучение и анализ происходящего",
"self":"внимательность и стремление понять больше",
"advice":"наблюдай и не делай поспешных выводов",
"image_id":"AgACAgIAAxkBAAIEdWnCl1b1IOnBV960biy5ezGTiTOaAAJSEmsbLWQZSmSAWQifI4ZGAQADAgADeQADOgQ"},

{"name":"Рыцарь Мечей","arcana":"minor","suit":"swords","keywords":["скорость"],
"general":"резкое движение вперед и напористые действия",
"love":"резкость и прямолинейность в отношениях",
"career":"рывок, активные действия и быстрые решения",
"self":"импульс и стремление действовать без задержек",
"advice":"контролируй скорость и не действуй необдуманно",
"image_id":"AgACAgIAAxkBAAIEd2nCl2O8IgMtqqnnVb8ujIggiggaAAJTEmsbLWQZSs2Wtsx4nELhAQADAgADeQADOgQ"},

{"name":"Королева Мечей","arcana":"minor","suit":"swords","keywords":["ясность"],
"general":"логика, ясность мышления и объективный взгляд на ситуацию",
"love":"эмоциональная сдержанность и стремление к честности",
"career":"анализ, принятие решений на основе фактов",
"self":"разум, способность отделять эмоции от реальности",
"advice":"будь объективен и смотри на ситуацию без иллюзий",
"image_id":"AgACAgIAAxkBAAIEeWnCl29n7l65Lf1ovoijirPehbTnAAJVEmsbLWQZSr42QD2kO46nAQADAgADeQADOgQ"},

{"name":"Король Мечей","arcana":"minor","suit":"swords","keywords":["контроль"],
"general":"ясное мышление, контроль и стратегический подход",
"love":"строгость и рациональный подход к чувствам",
"career":"управление, принятие взвешенных решений",
"self":"дисциплина и контроль над мыслями",
"advice":"думай стратегически и опирайся на разум",
"image_id":"AgACAgIAAxkBAAIEe2nCl3kRx2YUcTKFNlHaLBGHZtPoAAJWEmsbLWQZSr2teW3rRTQIAQADAgADeQADOgQ"},

# =====================
# ПЕНТАКЛИ (14)
# =====================

{"name":"Туз Пентаклей","arcana":"minor","suit":"pentacles","keywords":["шанс"],
"general":"новая материальная возможность, шанс на стабильность и рост",
"love":"стабильные и надежные отношения с перспективой развития",
"career":"новый источник дохода или перспективный проект",
"self":"наличие ресурсов и готовность использовать возможности",
"advice":"используй шанс и действуй практично",
"image_id":"AgACAgIAAxkBAAIEfWnCl5UgZ_44Onjh72vEtXHuUS9BAAJZEmsbLWQZStCj-O47xD6YAQADAgADeQADOgQ"},

{"name":"Двойка Пентаклей","arcana":"minor","suit":"pentacles","keywords":["баланс"],
"general":"необходимость удерживать баланс между разными задачами",
"love":"нестабильность и необходимость искать равновесие",
"career":"нагрузка и одновременное управление несколькими задачами",
"self":"адаптация к меняющимся условиям",
"advice":"держи баланс и не перегружай себя",
"image_id":"AgACAgIAAxkBAAIEf2nCl6DjuWtAKVnZpH4chNzAupr8AAJaEmsbLWQZSuMDpCqsExZfAQADAgADeQADOgQ"},

{"name":"Тройка Пентаклей","arcana":"minor","suit":"pentacles","keywords":["команда"],
"general":"совместная работа и достижение результата через сотрудничество",
"love":"поддержка и совместное развитие отношений",
"career":"работа в команде и признание усилий",
"self":"рост через взаимодействие с другими",
"advice":"работай вместе с другими и принимай помощь",
"image_id":"AgACAgIAAxkBAAIEgWnCl6xBkM82DHPsPJBNdcLUEfEzAAJbEmsbLWQZSlP6Ll_5SZqRAQADAgADeQADOgQ"},

{"name":"Четверка Пентаклей","arcana":"minor","suit":"pentacles","keywords":["контроль"],
"general":"стремление удержать стабильность и контроль над ресурсами",
"love":"закрытость и страх потерять контроль в отношениях",
"career":"стабильность, но без развития из-за осторожности",
"self":"привязанность к безопасности и страх изменений",
"advice":"расслабься и не держись за все слишком сильно",
"image_id":"AgACAgIAAxkBAAIEg2nCl7g5W-3Ll2t0-2Vu7_b_KvT_AAJcEmsbLWQZSj48Vxc_gft-AQADAgADeQADOgQ"},

{"name":"Пятерка Пентаклей","arcana":"minor","suit":"pentacles","keywords":["потеря"],
"general":"период трудностей и нехватки ресурсов",
"love":"кризис и ощущение одиночества в отношениях",
"career":"финансовые сложности или нестабильность",
"self":"чувство нехватки и уязвимости",
"advice":"ищи помощь и не замыкайся в проблеме",
"image_id":"AgACAgIAAxkBAAIEhWnCl8kfUfwC4IydpPAw8POGSL-zAAJdEmsbLWQZSgsGpts74HlgAQADAgADeQADOgQ"},

{"name":"Шестерка Пентаклей","arcana":"minor","suit":"pentacles","keywords":["обмен"],
"general":"баланс между отдачей и получением, поддержка и помощь",
"love":"взаимная поддержка и забота",
"career":"помощь или справедливое распределение ресурсов",
"self":"умение делиться и принимать",
"advice":"делись, но сохраняй баланс",
"image_id":"AgACAgIAAxkBAAIEh2nCl9W7euJ6InElyoZv337YmK7EAAJeEmsbLWQZSvrU10d0V4gnAQADAgADeQADOgQ"},

{"name":"Семерка Пентаклей","arcana":"minor","suit":"pentacles","keywords":["ожидание"],
"general":"оценка результатов и необходимость терпения",
"love":"пауза и ожидание развития ситуации",
"career":"анализ вложенных усилий и ожидание результата",
"self":"терпение и переоценка своих действий",
"advice":"подожди и не торопи события",
"image_id":"AgACAgIAAxkBAAIEiWnCl-IM4xS8RLSe0VHuLdlDafruAAJfEmsbLWQZShaSHJBejEAjAQADAgADeQADOgQ"},

{"name":"Восьмерка Пентаклей","arcana":"minor","suit":"pentacles","keywords":["работа"],
"general":"погружение в работу и развитие навыков",
"love":"постепенное развитие через усилия",
"career":"усердная работа и рост мастерства",
"self":"концентрация и развитие через практику",
"advice":"работай и совершенствуйся",
"image_id":"AgACAgIAAxkBAAIEi2nCl-_KZW5KAm7qf5KPViT2cVOIAAJgEmsbLWQZSlOBTE7pC-blAQADAgADeQADOgQ"},

{"name":"Девятка Пентаклей","arcana":"minor","suit":"pentacles","keywords":["достаток"],
"general":"материальный успех и ощущение независимости",
"love":"независимость и комфорт в отношениях",
"career":"стабильный доход и достигнутый результат",
"self":"самодостаточность и уверенность в себе",
"advice":"наслаждайся тем, что уже создано",
"image_id":"AgACAgIAAxkBAAIEjWnCmAGtXKi5DdEwGp7MJaiIUbDfAAJhEmsbLWQZSieq_ZNXurtPAQADAgADeQADOgQ"},

{"name":"Десятка Пентаклей","arcana":"minor","suit":"pentacles","keywords":["богатство"],
"general":"долгосрочная стабильность и устойчивый успех",
"love":"семья, надежность и прочная связь",
"career":"успех и закрепленный результат",
"self":"уверенность в будущем и ощущение опоры",
"advice":"цени стабильность и то, что уже создано",
"image_id":"AgACAgIAAxkBAAIEj2nCmA2J9R7VwMs1ZMHD4I9FEY5wAAJjEmsbLWQZSnge8vOE_spgAQADAgADeQADOgQ"},

{"name":"Паж Пентаклей","arcana":"minor","suit":"pentacles","keywords":["обучение"],
"general":"новые знания и начало пути в развитии навыков",
"love":"интерес и постепенное развитие чувств",
"career":"обучение или начало нового профессионального пути",
"self":"желание развиваться и узнавать новое",
"advice":"учись и вкладывайся в развитие",
"image_id":"AgACAgIAAxkBAAIEkWnCmBnRIihfBcTB-BQBWQAB4lnWigACZBJrGy1kGUqku_Zs_fMDRgEAAwIAA3kAAzoE"},

{"name":"Рыцарь Пентаклей","arcana":"minor","suit":"pentacles","keywords":["стабильность"],
"general":"постепенное движение к цели через упорство",
"love":"медленное, но надежное развитие отношений",
"career":"стабильная работа и последовательные действия",
"self":"упорство и выдержка",
"advice":"не спеши и двигайся последовательно",
"image_id":"AgACAgIAAxkBAAIEk2nCmCb5s07MBAh_qy4_gT1HFQFqAAJlEmsbLWQZSqDDflNxHVMVAQADAgADeQADOgQ"},

{"name":"Королева Пентаклей","arcana":"minor","suit":"pentacles","keywords":["забота"],
"general":"практичность, забота и умение создавать комфорт",
"love":"тепло, забота и стабильность в отношениях",
"career":"стабильность и умение управлять ресурсами",
"self":"ощущение комфорта и уверенности",
"advice":"заботься о себе и о том, что для тебя важно",
"image_id":"AgACAgIAAxkBAAIElWnCmDCdgII6f7fVW2jR7SZcLS5LAAJmEmsbLWQZSo0DbDZbyzufAQADAgADeQADOgQ"},

{"name":"Король Пентаклей","arcana":"minor","suit":"pentacles","keywords":["богатство"],
"general":"устойчивый успех, контроль и уверенность в материальной сфере",
"love":"надежность, стабильность и зрелые отношения",
"career":"бизнес, управление и финансовый контроль",
"self":"контроль над ресурсами и уверенность в своих силах",
"advice":"управляй разумно и укрепляй свою базу",
"image_id":"AgACAgIAAxkBAAIEl2nCmDozQXrhtKNQhTo0SypWRjTIAAJnEmsbLWQZSsGLubalEVcKAQADAgADeQADOgQ"}

]